apiVersion: v1
kind: Service
metadata:
        name: myapp-service

spec:
        type: NodePort

        ports:
                - targetPort: 3001
                  port: 81
                  nodePort: 30002

        selector:
                app: api_ex

